### ISSUE TITLE
Could I suggest Something

### ISSUE THREAD

**Issue by whitepik101** [SanAndreasP/ClaySoldiersMod#113]
1: Nexus can be repaired by soldiers
2: Nexus inventory
3: Number of soldiers allowed at one point to be variable instead of just being 10 for the nexus
4: Nexus healing nearby soldiers
5: soldiers having more things like the emerald and quartz (magic things)
6: Having something like the old "Clay Cookie"

If you need any help with any graphical stuff I will be more than happy to apply :)

**Comment by whitepik101** [comment]
I just really love this mod <3

**Comment by SanAndreasP** [comment]
1. Maybe an option for glistering melon soldiers, possibly toggleable in the nexus
2. planned
3. planned
4. Possibly, have to think about that
5. Suggestions for this would be nice. We don't have anything else planned right now in this direction.
6. planned

**Comment by whitepik101** [comment]
5. maybe eye of ender for a damage aura or an ice block for a slow area (like quartz)

**Comment by whitepik101** [comment]
another load of ideas (sorry)
1. maybe stained glass for tinted goggles
2. hardened clay (improvement on gravel)
3. TNT for kamikaze soldier
4. netherrack for immunity to fire damage
5. pressure plate shield from physical damage and projectiles
6. wood logs for building (readded)
7. maybe some item to establish relationships between colors (make them allies towards each other but hostile to others)
8. unicorn
9. soul sand self revive
10. clay horse armor
11. sitting
12. fishing rod grappling hook
13. something for life steal

not a suggestion but lily pads do not work (sinking and drowning)

**Comment by whitepik101** [comment]
another problem is ender pearl zombies are hostile towards different colored zombies plz fix

**Comment by SanAndreasP** [comment]
so, finally responding to this issue :P
1. we'll think about some kind of use for eye of enders. Your suggestion is noted.

1. planned
2. Maybe
3. already used as an infinite provider of the gunpowder upgrade
4. Fire Resistance potions work, but will look into it
5. There are bowl shields (which can be studded with an iron block) already
6. As I've explained in #17, I may extract the building aspect into its own village-themed addon
7. Maybe
8. Horses and pegasi are already enough for those kind of mounts. What would they do differently?
9. mmmmaybe
10. there's something like this planned
11. You mean sitting while idle? planned
12. Fishing rod falls under the same category as pickaxes/hoes/shovels/swords: They're too big and can't be picked up
13. You mean like a vampiric power? We'll think about it...

The ender pearl zombies will be fixed in the next release

**Comment by whitepik101** [comment]
I thought the unicorn could have an ability to deal ranged damage or any soldier riding it has extra damage

**Comment by whitepik101** [comment]
Hi it's me again
1: Poisonous ranged weapon
2: prismarine for thorns (block for infinite)
3: Buckets for helmets (infinite?)
4: Granite Andesite and Diorite for something (Armour buffs + slower? )
5: Carpets for shoes
6: Golden apple for something (short damage buff, regeneration and resistance)
7: Behavior change (Tendency to go on beds is annoying)
8: More config options
9: More generated structures
(are you going to port it to 1.8 or keep it at 1.7 and just keep on updating like other mods (buildcraft etc...))

**Comment by MBTshock** [comment]
Where do u get these EPIC ideas?

**Comment by ispy92** [comment]
You should try to make a use for every minecraft item, and if the item is too big for a soldier, then make a smaller version of it like you did with the shears. This would be difficult but worth it. I'm going to go through all the items of minecraft and list them here. Also you should add a book that tells tells people what every item does to the soldiers. In the book you should add a search bar so that you could find blocks easly. this book would be the best, and please make a crafting recipe so that I don't have to run around the world looking for it in dungeons.

1. you should be able to throw stone or cobblestone or anything like that into a crafting table and get rocks to throw
2. you could also make a clay tree ent. This may be pretty crazy but you could include a sapling in the crafting recipe so that you don't just have sapling clutter.
3. string should turn a solder into a spider or add a spider mount. the spider should be able to trap a clay soldier kind of like slime but it can trap their mounts as well or it lasts longer
4. a chest should make it so that a soldier has an inventory so that you can put items in it, like gravel so that he is like a resupply soldier for other soldiers to take from his inventory
5. you should make a device like the clay disrupter, but it freeze all the soldiers in a radius until you press the device again
6. if you give a soldier a ladder they should be able to climb up a few blocks, but they cannot climb indefinitely

Those are a few ideas I have. I may post more in the future. I have many more ideas but I don't have time right now

**Comment by whitepik101** [comment]
I believe string is used for immunity to explosions

**Comment by whitepik101** [comment]
MBTshock I just kinda come up with them :/
more ideas.

1: a kind of barrier to allow certain colours through but not others
2: Enchanted book for an enchantment shine (like enchanted golden apples) on soldiers (infinite source)
3: if nether star isn't used for anything in the future maybe it can be used to create a soldier that buffs nearby soldiers (like a beacon)
4: Mini fishing rods for grappling hook (crafted with 2 sticks 1 string)
5: sponge or slime block for a trampoline (placed on the ground)

**Comment by whitepik101** [comment]
by trampoline I mean it launches them high up not bounces them

**Comment by whitepik101** [comment]
1: something to render a soldier completely useless (stuns soldiers and stops them from attacking other soldiers, maybe for spider webs?(slime balls still allow them to attack and redstone makes them swing around blindly so they can still attack))
2: milk is amazing and should be used someway (immunity to negative/ any potion effects or mini strength buff/attack speed up)
3: water bottles/ buckets for AoE water projectiles causing weakness to any soldier hit (because clay softens when wet :3)
4: soldiers riding turtles should get a speed/strength boost in water


@ispy92 I support the spider idea + spider riders shouldn't be slowed by webs maybe hardened clay spiders :3 but weaker than geckos + poison?

**Comment by qwerty682** [comment]
How about the ability to change the Nexus's health?

**Comment by ACcrafter** [comment]
PLEASE ADD ALL OF THOSE THAT WOULD MAKE THE MOD MORE FUN!!!!!!!!!¡!!!!¡!!!!!¡¡!!!!!!

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
