### ISSUE TITLE
About clay soliders

### ISSUE THREAD

**Issue by ZorgoII** [SanAndreasP/ClaySoldiersMod#149]
when i drop them wood they wont pick it up.. i tried with stacks like 5,10,20.. but they are just passing by it and wont pick it up!.. please can i get some information on this. ty.

**Comment by MBTshock** [comment]
They are trying to fix it. Read other people's posts before you post!

**Comment by Spartan322** [comment]
#17 
Does anyone ever read the thread? Its been reported multiple times that the mod is being rewritten and that is one of the last things the devs care about right now (and don't argue about it, its called clay soldiers, so that's not the focus, and we have already had this discussion at least 4 times now)

Btw, that is such a useless title, if you are going to submit an issue, name it something descriptive and useful.

**Comment by ZorgoII** [comment]
Ok. Tnx for nothing.. U rly help people around here.. Good for you.

**Comment by Spartan322** [comment]
I'm just giving you information, snapping at someone insignificant doesn't help (I've been around a lot but my representation is of no one but myself)

**Comment by SanAndreasP** [comment]
As  @Spartan322 said, #17 explains it.
