### ISSUE TITLE
Bug - Soldiers won't pick up wood or take items out of chests.

### ISSUE THREAD

**Issue by LittleBit12** [SanAndreasP/ClaySoldiersMod#17]
I'm running 1.7.10, forge, and the correct manager pack. Everything seems to work fine except for these two features. I've dropped wood on the ground in every combination - stacks of 5, 10, 20, 64, you name it, they'll ignore it. I attempted to get the little soldiers to take the wood out of a chest, but they wouldn't. I decided to try putting other items in the chest, and they wouldn't take those, either. Any thoughts on what could be the issue?

**Comment by ryan24davis** [comment]
He said them building houses isn't a priority fix which me and lots of other people say it is, I've already told him my reason for why it should be done and he just went around everything I said and just said there soldiers not builders and then closed it for discussion which is showing he doesn't even care it's just easier to make upgrades then buildings I guess.

**Comment by SanAndreasP** [comment]
Well, he already told you to go to the forum to discuss this topic if you disagree with our decision.
The main goal for this mod is to have tiny little soldiers fighting each other, gladiator style, you see how the building is not really a main part of this mod?
Currently this mod is not "feature complete" enough to add the building aspect back in. And yes, you're right, it is indeed easier to add upgrades then to recode the building system.

If you really can't wait and know how to code, then you're free to fork this repo, re-implement the building system and make a pull request, any help is appreciated!

**Comment by SanAndreasP** [comment]
A note to this "building issue":
The building thing is not really a main theme of this mod (and, according to the creator of this mod [KodaichiZero], it was just added because many people kept pestering him to add it), like we've explained numerous times.
We kept it during the "old mod updates" before the Rewrite™ because it was just easier to keep it than to remove it (the code for it didn't change up until the Rewrite™).

So yeah.. I'm playing with the thought of having this (and possibly even other villager features like farming, mining etc.) existing as a seperate add-on to the mod. But that'll be a thought when the mod is out of beta.


In regards to the chests: It will be fixed in the next release.

**Comment by Spartan322** [comment]
@SanAndreasP If you'd like help with the villager addon, I'd be happy to help when I have time, I have a couple other mods, but most are stuck (in a type of dev hell that I can't help) due to my current situation, so I kinda am forced to have time. If you'd like me to start a repo for it at any time (if you're fine with that), just tell me so, or just open a new repo and I'll just push to it for a good sum of time. (for now)

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
