### ISSUE TITLE
I noticed that yes the soldiers hug the walls and have very slow movement speed, it just seems like their a.i. is slowed down

### ISSUE THREAD

**Issue by mbfree** [SanAndreasP/ClaySoldiersMod#189]
Make sure you check following things before you open a new issue:

[ ] Check that you use Java 8
[ ] Check that you use the latest MinecraftForge version available for your version of Minecraft
[ ] Check that you use the Minecraft version supported by the mod

Put the answers below the following questions:
 -What version of Minecraft do you use?
 
 
 -What version of MinecraftForge do you use?

 -What version of SanLib do you use?
 
 
 -What is the issue / bug you have encountered? Give us a short description.

 -How can it be reproduced?

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:

**Comment by SanAndreasP** [comment]
1. Next time fill out the form provided and don't just put the whole issue description into the title. Thanks.
2. Soldiers hugging the wall: can you provide a picture? They only will hug the walls in very confined spaces. That's because of the collision system in MC.
3. Slow AI: The problem with the new AI system from Minecraft I have to use is it just checks every 3rd tick or so for an update, probably because of performance reasons!?
Are the soldiers walking slow when idle or attacking?

**Comment by mbfree** [comment]
Yes, the soldiers are walking slow and are idle, it might be my system. I built a little town around an arena and they hug corners whenever there not fighting. A lot of them gather up and hug the corners of buildings. What I meant by the AI being slow is that they seem to react a bit slower. But I also noticed another issue when in the arena with multiple colors while the match hasn't started they all seemed agro to each other when the can't see each other. Also sorry about 

being stupid and just making a title.
![screen shot 2017-02-20 at 9 47 13 pm](https://cloud.githubusercontent.com/assets/25809175/23152319/2c46c996-f7b6-11e6-84b3-c5cf6131f5b3.png)

**Comment by SanAndreasP** [comment]
Them getting aggro when they can't see eachother I hopefully fixed.
This may be the same issue with them hugging the walls, since I've not noticed it after the fix.
Them reacting a bit slow I fixed as well, I think. I've tweaked the AI in that regard.
I can increase the speed in which they're walking at, but for that, maybe it's alright after the fixes are released.

So yeah, I hopefully fixed all of it with the new upcoming release (which should be soon-ish)

**Comment by mbfree** [comment]
Ok, thanks. Other than that I've noticed the tab in the creative menu is just a scramble of letters.

**Comment by mbfree** [comment]
I also noticed something recently when I boot up minecraft with the mod the screen spazzes out when the main menu shows up.

**Comment by SanAndreasP** [comment]
I suspect the initial issue is fixed!?
I'll close this. If there's any more issues with the latest version, please open up a new PR.
