### ISSUE TITLE
Soldiers get stuck in corners.

### ISSUE THREAD

**Issue by nldreyer** [SanAndreasP/ClaySoldiersMod#219]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.10.2]

What version of MinecraftForge do you use?
[forge-12.18.3.2511]

What version of SanLib do you use?
[SanLib-1.10.2-1.3.0.jar]

What version of Clay Soldiers do you use?
[ClaySoldiersMod-1.10.2-3.0.0.-alpha.2.jar]
 
What is the issue / bug you have encountered? Give us a short description.
[Soldiers occasionally get stuck in corners.]

How can it be reproduced?
[Mass amounts of soldiers in a large battle. Only way I have seen it.]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[Link to log file]

**Comment by SanAndreasP** [comment]
The 1.10.2 version is not actively developed anymore (I have limited time, so I'm unable to maintain multiple MC versions on my own)
CSM is now on Alpha 9.1 on 1.12.2, which has a bunch of AI fixes included since Alpha 2, so you may wanna try that out if possible.

If you have the same issues on the Alpha 9.1 version, please open up a new issue, thanks.
