### ISSUE TITLE
infinite shooting

### ISSUE THREAD

**Issue by po123po** [SanAndreasP/ClaySoldiersMod#36]
can u make clay soldiers shoot infinitely?
because now clay soldiers's ammo are limited

**Comment by SanAndreasP** [comment]
* It adds a disadvantage to the meelee soldiers (since their weapons can break)
* There'll be less variety (now the soldier has to go meele if he runs out, otherwise ranged soldiers could just throw endless stuff at others and not be hurt once w/o other opposing ranged ones)
* It's more logical for them to "lose" material as they throw projectiles

So, no.
