### ISSUE TITLE
Im Crashed and i ave all last version 

### ISSUE THREAD

**Issue by Fredodo82** [SanAndreasP/ClaySoldiersMod#47]
Im crashed and i im all last version ( Mac,Java,Clay Soldier,SAPManPack )

https://www.youtube.com/watch?v=sfoZv3Bk3tg

.DS_Store d'onts reponsibility for Crashed

**Comment by Fredodo82** [comment]
it is SAPManPack for crashed

**Comment by Fredodo82** [comment]
im resolved crashed ( forge for last version is note compatibel for SAPManPack )

**Comment by Spartan322** [comment]
I don't know about San, but I think a crash log would be easier to read. A video of the crash log doesn't really help much (or as much) compared to a crash log because we can cycle through the info on our own volition. Also the crash log tells us everything you just showed in the video. Could you post the crash log on http://pastebin.com/ or https://gist.github.com/ and give the link here. That would be best.

**Comment by SanAndreasP** [comment]
I already see your problem in your executable path inside your profile settings.

See #23

**Comment by Fredodo82** [comment]
log https://gist.github.com/Fredodo82/a038f1de72267cbfd136
