### ISSUE TITLE
When is the next update coming and will there be a bug fix for the clay soldiers not building houses in it.

### ISSUE THREAD

**Issue by theminecraften66** [SanAndreasP/ClaySoldiersMod#61]
Hi SanAndreasP i was wondering when the next update is coming out for 1.7.10 or if it will be for 1.8 also if u will fix the problem with the clay soldiers not building houses. also if u are going to add new houses for them to build. like castles and stuff. not trying to be pushe. just asking. =)

**Comment by SanAndreasP** [comment]
When it's done.™
Next update will be for 1.7.10, I dunno when I'll start working on a 1.8 version, probably not soon, though.

Also see #17 for the buildings. They are low prioroty.

**Comment by theminecraften66** [comment]
y are they low prioroty. not to be pushey but they where my faverate part of the mod. thanks though for repling anyway. best of luck on the update and such. =)

**Comment by SanAndreasP** [comment]
Because building stuff is not really their main goal. They're fighters.

**Comment by theminecraften66** [comment]
ok. thanks for the answer. it helps explain alot.

**Comment by ryan24davis** [comment]
Wow I think building should be a priority because without it the mod gets boring, you give them upgrades and watch them fight for about 2 hours and then your done, giving them wood and watching them build up a village to defend and fight in is fun because you can set up raids and stuff. Upgrades get boring, building a village with a huge army to defend it is fun. It is MineCraft after all, ment for building not watching fights.

**Comment by Spartan322** [comment]
this is seems like something to be discussed on the MC Forum Thread.

**Comment by CliffracerX** [comment]
Even if building is exciting and all, these *are* supposed to be little toy soldiers.  SOLDIERS.  Soldiers are supposed to fight, maybe building on occasion to defend themselves, not building villages to start fights over.  Bugfixes and the missing upgrades take somewhat higher priority over building.

*Take further discussion to the Minecraft Forums thread*
