### ISSUE TITLE
NEI (Not Enough Items)

### ISSUE THREAD

**Issue by HeroUltraOmega** [SanAndreasP/ClaySoldiersMod#92]
I don't know whether this is an issue or intended, but when looking up MOST recipes of this mod while in NEI mod they do not show up. Two recipes I remember working properly is the clay soldier recipe, (not the colored ones,) Clay Disruptor, Hardened Clay Disruptor, Clay Statistics Display, and the Shear Blade. The other clay ones don't show up.

**Comment by Spartan322** [comment]
I believe NEI reads the recipes, so this is an NEI problem, not a Clay Solder problem.

**Comment by SanAndreasP** [comment]
That is because we use a custom IRecipe and as such, NEI can't read it. We would need to make a compatibility patch like I did on here [SanAndreasP/VarietyChests/NeiRecipesPlainChests.java](https://github.com/SanAndreasP/VarietyChests/blob/master/java/de/sanandrew/mods/varietychests/util/modcompat/nei/NeiRecipesPlainChests.java)

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
